# Generated by Django 4.2 on 2023-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'choix',
            },
        ),
    ]
