# Generated by Django 4.2 on 2023-04-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant_candidat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condidat',
            old_name='spécailité',
            new_name='specailite',
        ),
    ]
