# Generated by Django 4.2 on 2023-04-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrative_staff', '0002_alter_sujet_id_concours'),
        ('Enseignant_candidat', '0004_alter_reclamation_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choix',
            name='id_condidat',
            field=models.ForeignKey(db_column='id_condidat', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.condidat'),
        ),
        migrations.AlterField(
            model_name='choix',
            name='id_these',
            field=models.ForeignKey(db_column='id_these', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.these'),
        ),
        migrations.AlterField(
            model_name='condidat',
            name='id_concours',
            field=models.ForeignKey(db_column='id_concours', on_delete=django.db.models.deletion.CASCADE, to='Administrative_staff.concours'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='code_anonyme_condidat',
            field=models.ForeignKey(db_column='code_anonyme_condidat', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.condidat', to_field='code_anonyme'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='id_enseignant',
            field=models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.enseignant'),
        ),
        migrations.AlterField(
            model_name='notification_condidats',
            name='id_condidat',
            field=models.ForeignKey(db_column='id_condidat', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.condidat'),
        ),
        migrations.AlterField(
            model_name='notification_enseignants',
            name='id_enseignant',
            field=models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.enseignant'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='id_condidat',
            field=models.ForeignKey(db_column='id_condidat', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.condidat'),
        ),
    ]
