# Generated by Django 4.2 on 2023-04-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant_candidat', '0005_alter_choix_id_condidat_alter_choix_id_these_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='id_enseignant',
            field=models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.enseignant'),
        ),
        migrations.AlterField(
            model_name='these',
            name='id_enseignant',
            field=models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='Enseignant_candidat.enseignant'),
        ),
    ]
