# Generated by Django 4.2 on 2023-04-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id_annonce', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'annonce',
            },
        ),
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id_concours', models.AutoField(primary_key=True, serialize=False)),
                ('salle', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('annee_concours', models.DateField()),
            ],
            options={
                'db_table': 'concours',
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id_sujet', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('type', models.BooleanField(default=False)),
                ('id_concours', models.OneToOneField(db_column='id_concours', on_delete=django.db.models.deletion.CASCADE, to='Administrative_staff.concours')),
            ],
            options={
                'db_table': 'sujet',
            },
        ),
    ]
