# Generated by Django 4.2 on 2023-04-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrative_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='id_concours',
            field=models.ForeignKey(db_column='id_concours', on_delete=django.db.models.deletion.CASCADE, to='Administrative_staff.concours'),
        ),
    ]
